file:
  # use_llama_parse: Use LlamaParse if `true`. Needs a `LLAMA_CLOUD_API_KEY` from https://cloud.llamaindex.ai set as environment variable
  use_llama_parse: false

# web:
#   driver_arguments:
#     # The arguments to pass to the webdriver. E.g.: add --headless to run in headless mode
#     - --no-sandbox
#     - --disable-dev-shm-usage
#   urls:
#     # base_url: The URL to start crawling with
#     # prefix: Only crawl URLs matching the specified prefix
#     # depth: The maximum depth for BFS traversal
#     # You can add more websites by adding more entries (don't forget the - prefix from YAML)
#     - base_url: https://panelexpertos.cl/
#       prefix: https://panelexpertos.cl/
#       depth: 1

dbmetadata:
  # The configuration for the database loader, only supports MySQL and PostgreSQL databases for now.
  # uri: The URI for the database. E.g.: mysql+pymysql://user:password@localhost:3306/db or postgresql+psycopg2://user:password@localhost:5432/db
  # query: The query to fetch data from the database. E.g.: SELECT * FROM table
  # QA STDE
  - uri: mysql+pymysql://user:pass@localhost:3306/mydb
  # - uri: mysql+pymysql://user:pass@localhost:3306/mydb
    queries:
      - SELECT
          RIGHT('0' || CAST(d.number AS text), 2) || '-' || CAST(DATE_PART('year', d.created_at) AS text) AS discrepancia,
          d.cover AS descripcion,
          TO_CHAR(d.created_at, 'MM/DD/YYYY HH24:MI') AS fecha,
          mt.materia,
          mt.submateria,
          CASE
              WHEN COALESCE(doc.document_type_id, 0) IN (3, 11) THEN TO_CHAR(doc.created_at, 'MM/DD/YYYY HH24:MI')
              ELSE ''
          END AS fechafinaliza,
          CASE
              WHEN COALESCE(doc.document_type_id, 0) = 3 THEN 'Dictamen'
              WHEN COALESCE(doc.document_type_id, 0) = 11 THEN 'Allanamiento/Desistimiento'
              ELSE ''
          END AS doctofinaliza
        FROM discrepancies d
        INNER JOIN (
          SELECT lsm.id, lsm.name AS submateria, lm.name AS materia
          FROM legal_sub_matters lsm
          INNER JOIN legal_matters lm ON lsm.legal_matter_id = lm.id
        ) mt ON mt.id = d.legal_sub_matter_id
        LEFT JOIN documents doc ON doc.discrepancy_id = d.id AND doc.document_type_id IN (3, 11)
        WHERE d.created_at IS NOT NULL;
